---
title: ReproRes 2022
output: md_document
---

* Office hours: Fridays 11:00 - 12:00 in Lisa's office (R524, 62 Hillhead Street) or [Zoom](https://uofglasgow.zoom.us/my/debruine)
* [Collaborative Class Notes](https://docs.google.com/document/d/1ZSSg7UjnZGvuR3-gSnYdTEZWPIvuFrRTPLhjpeLtkzc/)

## Class 03 (2022-10-07)

### Pre-class

-   Read [Chapter 3: Data Visualisation](https://psyteachr.github.io/reprores-v3/ggplot.html)
-   Complete the
    [exercises](https://psyteachr.github.io/reprores-v3/exercises.html)
    for chapter 3
-   Fill out the [pre-class poll](https://forms.gle/RzuYHaA9jpkStner6)

### In-Class

-   Open the [class book](https://psyteachr.github.io/reprores-v3/)
-   Open RStudio
-   Set up class project
-   Introduction to the mid-term assessment
-   work on Chapter 3 exercises in groups
-   break
-   Present chapter 3 exercises

## Class 02 (2022-09-30)

* [Poll 2](https://debruine.github.io/reprores_2022/polls/poll-02.html)

### Pre-class

-   Read [Chapter 2: Reproducible
    Workflows](https://psyteachr.github.io/reprores-v3/repro.html)
-   Complete the
    [exercises](https://psyteachr.github.io/reprores-v3/exercises.html)
    for chapter 2
-   Fill out the [pre-class poll](https://forms.gle/6ZiotbRgWPy79nhs9)
-   Fill out the [office hours when2meet](https://www.when2meet.com/?16977819-cpkIB)

### In-Class

-   Open the [class book](https://psyteachr.github.io/reprores-v3/)
-   Open RStudio
-   Set up class project
-   cowsay
-   Chapter 2 questions
-   break
-   Chapter 2 exercise walkthrough

### Class Notes

-   Please take notes in the [Collaborative Class Notes](https://docs.google.com/document/d/1ZSSg7UjnZGvuR3-gSnYdTEZWPIvuFrRTPLhjpeLtkzc/) google doc
-   Office hours will be Fridays 11:00 - 12:00, normally in Lisa's office (R524 in 62 Hillhead Street) or by [Zoom](https://uofglasgow.zoom.us/my/debruine). You can also arrange individual meetings if that time doesn't work for you.

### After Class

-   Read [Chapter 3: Data Visualisation](https://psyteachr.github.io/reprores-v3/ggplot.html)
-   Complete the
    [exercises](https://psyteachr.github.io/reprores-v3/exercises.html)
    for chapter 3
-   Complete the (optional) [data skills
    self-assessment](https://moodle.gla.ac.uk/mod/assign/view.php?id=3103593)

## Class 01 (2022-09-23)
<!--
* [Recording](): check the Teams channel for the recording passcode
-->
* [Poll 1](https://debruine.github.io/reprores_2022/polls/poll-01.html)

### Pre-class 

- Read [the intro](https://psyteachr.github.io/reprores-v3/) 
- Install R and RStudio (if using your own laptop in class)
- Read [Chapter 1: Getting Started](https://psyteachr.github.io/reprores-v3/intro.html) 
- Complete the [exercises](https://psyteachr.github.io/reprores-v3/exercises.html) for chapter 1
- Fill out the [pre-class poll](https://forms.gle/m6MuVqLpxoakyCGk7)

### In-Class

- Open the [class book](https://psyteachr.github.io/reprores-v3/)
- Open RStudio 
- Start at 13:05 (remind Lisa to start recording!)
- [Why Code?](https://debruine.github.io/why-code/) presentation
- Discuss the [class syllabus](https://moodle.gla.ac.uk/course/view.php?id=33447&section=1)
- Discuss the [data skills self-assessment](https://moodle.gla.ac.uk/mod/assign/view.php?id=3103593)
- Break
- Chapter 1 exercises

### Class Notes

- log into desktops with campus\12345678X and GUID password
- `fortunes` not available for R 4.2


### After Class

- Read [Chapter 2: Reproducible Workflows](https://psyteachr.github.io/reprores-v3/repro.html)
- Complete the [exercises](https://psyteachr.github.io/reprores-v3/exercises.html) for chapter 2
- Complete the (optional) [data skills self-assessment](https://moodle.gla.ac.uk/mod/assign/view.php?id=3103593)
